// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Session struct {
	ID           uuid.UUID
	Sessiontoken string
	Userid       []byte
	Expires      time.Time
	Createdat    time.Time
	Updateat     time.Time
}

type User struct {
	ID            uuid.UUID
	Name          string
	Email         string
	Emailverified sql.NullTime
	Policy        int32
	Password      string
	Createdat     time.Time
	Updateat      time.Time
}
