// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Session struct {
	ID           uuid.UUID
	SessionToken string
	UserID       uuid.UUID
	Expires      time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type User struct {
	ID            uuid.UUID
	Name          string
	Email         string
	EmailVerified sql.NullTime
	Policy        int32
	Password      string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
