// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package models

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (id, name, email, password, policy)
VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID       uuid.UUID
	Name     string
	Email    string
	Password string
	Policy   int32
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Policy,
	)
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = id
`

func (q *Queries) DeleteUser(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUser)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, emailverified, policy, password, createdat, updateat FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Emailverified,
		&i.Policy,
		&i.Password,
		&i.Createdat,
		&i.Updateat,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, emailverified, policy, password, createdat, updateat FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Emailverified,
		&i.Policy,
		&i.Password,
		&i.Createdat,
		&i.Updateat,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, emailverified, policy, password, createdat, updateat FROM users
ORDER BY createdAt DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Emailverified,
			&i.Policy,
			&i.Password,
			&i.Createdat,
			&i.Updateat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :execresult
UPDATE users
SET name = name, email = email, emailVerified = emailVerified, password = password, updateAt = CURRENT_TIMESTAMP
WHERE id = id
`

func (q *Queries) UpdateUser(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUser)
}
