// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session.sql

package models

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, session_token, csrf_token, user_id, expires) VALUES ($1, $2, $3, $4, $5) RETURNING id, session_token, csrf_token, user_id, expires, created_at, updated_at
`

type CreateSessionParams struct {
	ID           uuid.UUID
	SessionToken string
	CsrfToken    string
	UserID       uuid.UUID
	Expires      time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.SessionToken,
		arg.CsrfToken,
		arg.UserID,
		arg.Expires,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SessionToken,
		&i.CsrfToken,
		&i.UserID,
		&i.Expires,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, session_token, csrf_token, user_id, expires, created_at, updated_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SessionToken,
		&i.CsrfToken,
		&i.UserID,
		&i.Expires,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
