name: "simple-go-project"

services:
  rabbitmq:
    image: "rabbitmq:4-alpine"
    container_name: rabbit
    ports:
      - "5672:5672"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - "./db-data/rabbitmq/:/var/lib/rabbitmq"
  mysql:
    image: "mysql:8.0.34"
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - "./db-data/mysql/:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=authentication
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    image: broker-service:latest
    container_name: broker
    ports:
      -  "8080:80"
    deploy:
      mode: replicated
      replicas: 1
  listener-service:
    build:
      context: ./../listener-service
      dockerfile: ./../listener-service/listener-service.dockerfile
    image: listener-service:latest
    container_name: listener
    ports:
      -  "8081:80"
    deploy:
      mode: replicated
      replicas: 1
  auth-service:
    build:
      context: ./../auth-service
      dockerfile: ./../auth-service/auth-service.dockerfile
    image: auth-service:latest
    container_name: auth
    ports:
      - "8082:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - DATABASE_URL=mysql://root:root@tcp(localhost:3306)/authentication