CREATE TABLE sessions (
  id UUID PRIMARY KEY,
  session_token VARCHAR(255) NOT NULL UNIQUE,
  csrf_token VARCHAR(255) NOT NULL UNIQUE,
  user_id UUID NOT NULL,
  expires TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);