// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: log.sql

package models

import (
	"context"
	"database/sql"
)

const createLog = `-- name: CreateLog :one
INSERT INTO log (id, message, thread_identifier, requestid, logtype, userid) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, message, thread_identifier, requestid, logtype, userid, created_at
`

type CreateLogParams struct {
	ID               int32
	Message          string
	ThreadIdentifier sql.NullString
	Requestid        sql.NullString
	Logtype          Logtype
	Userid           sql.NullString
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (Log, error) {
	row := q.db.QueryRowContext(ctx, createLog,
		arg.ID,
		arg.Message,
		arg.ThreadIdentifier,
		arg.Requestid,
		arg.Logtype,
		arg.Userid,
	)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.ThreadIdentifier,
		&i.Requestid,
		&i.Logtype,
		&i.Userid,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLog = `-- name: DeleteLog :exec
DELETE FROM log WHERE id = $1
`

func (q *Queries) DeleteLog(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteLog, id)
	return err
}

const getLogByID = `-- name: GetLogByID :one
SELECT id, message, thread_identifier, requestid, logtype, userid, created_at FROM log WHERE id = $1
`

func (q *Queries) GetLogByID(ctx context.Context, id int32) (Log, error) {
	row := q.db.QueryRowContext(ctx, getLogByID, id)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.ThreadIdentifier,
		&i.Requestid,
		&i.Logtype,
		&i.Userid,
		&i.CreatedAt,
	)
	return i, err
}

const getLogByLogType = `-- name: GetLogByLogType :many
SELECT id, message, thread_identifier, requestid, logtype, userid, created_at FROM log WHERE logtype = $1
`

func (q *Queries) GetLogByLogType(ctx context.Context, logtype Logtype) ([]Log, error) {
	rows, err := q.db.QueryContext(ctx, getLogByLogType, logtype)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.Message,
			&i.ThreadIdentifier,
			&i.Requestid,
			&i.Logtype,
			&i.Userid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLogByRequestID = `-- name: GetLogByRequestID :many
SELECT id, message, thread_identifier, requestid, logtype, userid, created_at FROM log WHERE requestid = $1
`

func (q *Queries) GetLogByRequestID(ctx context.Context, requestid sql.NullString) ([]Log, error) {
	rows, err := q.db.QueryContext(ctx, getLogByRequestID, requestid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.Message,
			&i.ThreadIdentifier,
			&i.Requestid,
			&i.Logtype,
			&i.Userid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLogByThreadIdentifier = `-- name: GetLogByThreadIdentifier :many
SELECT id, message, thread_identifier, requestid, logtype, userid, created_at FROM log WHERE thread_identifier = $1
`

func (q *Queries) GetLogByThreadIdentifier(ctx context.Context, threadIdentifier sql.NullString) ([]Log, error) {
	rows, err := q.db.QueryContext(ctx, getLogByThreadIdentifier, threadIdentifier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.Message,
			&i.ThreadIdentifier,
			&i.Requestid,
			&i.Logtype,
			&i.Userid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLogByUserID = `-- name: GetLogByUserID :many
SELECT id, message, thread_identifier, requestid, logtype, userid, created_at FROM log WHERE userid = $1
`

func (q *Queries) GetLogByUserID(ctx context.Context, userid sql.NullString) ([]Log, error) {
	rows, err := q.db.QueryContext(ctx, getLogByUserID, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.Message,
			&i.ThreadIdentifier,
			&i.Requestid,
			&i.Logtype,
			&i.Userid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
