// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/sqlc-dev/pqtype"
)

type Logtype string

const (
	LogtypeDebug   Logtype = "debug"
	LogtypeInfo    Logtype = "info"
	LogtypeWarning Logtype = "warning"
	LogtypeError   Logtype = "error"
	LogtypeFatal   Logtype = "fatal"
)

func (e *Logtype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Logtype(s)
	case string:
		*e = Logtype(s)
	default:
		return fmt.Errorf("unsupported scan type for Logtype: %T", src)
	}
	return nil
}

type NullLogtype struct {
	Logtype Logtype
	Valid   bool // Valid is true if Logtype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLogtype) Scan(value interface{}) error {
	if value == nil {
		ns.Logtype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Logtype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLogtype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Logtype), nil
}

type Log struct {
	ID               int32
	Message          string
	ThreadIdentifier sql.NullString
	Requestid        sql.NullString
	Logtype          Logtype
	Userid           sql.NullString
	CreatedAt        sql.NullTime
}

type Metric struct {
	ID         int32
	Histograms pqtype.NullRawMessage
	Counts     []int32
	Values     []float64
	CreatedAt  sql.NullTime
	Requestid  sql.NullString
}

type Request struct {
	ID        int32
	Requestid sql.NullString
	Code      sql.NullInt32
	Size      sql.NullInt32
	CreatedAt sql.NullTime
}
